#=================================================================================
#==========================   spring设置  =========================================
#==================================================================================

spring:
  main:
    lazy-initialization: false  #懒加载
  profiles:
    active: @spring.active@
  task:
    scheduling:
      pool:
        size: 10 #定时任务线程池大小设置默认1设置为5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss #jackson时间格式化类
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss #日期格式化
  servlet:
    multipart:
      max-request-size: 50MB
      file-size-threshold: 0 #文件写入磁盘的阈值,设置为0，即上传就存储在服务器,如果是100则表示小于100会存储在内存
      max-file-size: 50MB   #单个文件上传的最大值
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #用于连接本地数据库测试是否能正确运行
      url: mpw:9Qfp+NeifxXpSX+ITv7MfpotR3g8L5fzQF00xnqyv7/wdLLwLoVPisbUMlHnbW16TR09N/Nyzl9pebnV6UOma8TswK7LL3nC8ifSwa2vxnrD7DXVVPn8mKXpw2kKk92m0Nt5lBdu6ab2Mjxq/iEQGxs7PZP1Qga2Ne9XUtgkizc=
      username: mpw:wEL7uPAuz4hbK+kwKBGeiQ==
      password: mpw:OfGZyCjRemMXVySW/DkUWA==
      hikari:
          max-lifetime: 1800000  #连接的最大生命周期，表示一个连接在被关闭之前的最长使用时间。设置为30分钟（1800000毫秒）
  data:
      redis:
          port: 6379
          host: mpw:VlxmNwZH3XgRYqG/XKMXhg==
          password: mpw:OfGZyCjRemMXVySW/DkUWA==
          database: 0
server:
  port: 8080

#===========================================================================
#==========================mybatis配置=======================================
#============================================================================

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id #全局主键使用雪花算法生成id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql
  mapper-locations: "classpath:mapping/*.xml"

#=============================================================================
#========================  swagger 配置  =====================================
#=============================================================================

springdoc:
    api-docs:
        enabled: true   #是否开启文档功能关系到swagger-ui能否开启
        path: /v3/api-docs #swagger后端请求地址，查看swagger所有配置，同时也是配置web端的接口配置,必须写
    swagger-ui:
        tags-sorter: alpha  #标签排序
        operations-sorter: alpha  #操作排序
        path: /swagger  #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger会自动重定向到swagger页面注意是path不是url
    group-configs:
        - group: 测试API
          packages-to-scan:
              - com.jay.controller
knife4j:   # knife4j的增强配置，不需要增强可以不配
    enable: true  #开启访问默认路径doc.html
    setting:
        language: zh_cn
        enable-request-cache: false  #不开启缓存请求
    cors: true  #跨域请求
    production: false   #是否是生产环境，如果设置true,doc.html就不能访问
    basic:
        enable: @basic.enable@
        password: mpw:zp1SL9P56YSRX4kRau9R9A==
        username: mpw:PdBT4eeuJoG1NOtzH6onww==

#=============================================================================
#======================== 自定义配置  =========================================
#=============================================================================

auth-path:
    exclude:
        - /**/doc.html
        - /**/*.css
        - /**/*.js
        - /**/*.png
        - /**/*.jpg
        - /**/*.ico
        - /**/v3/**

save-path: @save.path@
