#测试环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用于连接本地数据库测试是否能正确运行
    url: mpw:9Qfp+NeifxXpSX+ITv7MfpotR3g8L5fzQF00xnqyv7/kATd4iiFdgNIzfHCy9vzl6jDRKuWoLOaZ5zRledf5oLoRmWa5FeICyOdEGIZpNRBitIgMfGr0GXZj5uT8DkNqcu1vpe93/75TaQ+t2pIZVjXLq3gUg9GXW+LnmB25Rjg=
    username: mpw:wEL7uPAuz4hbK+kwKBGeiQ==
    password: mpw:OfGZyCjRemMXVySW/DkUWA==
    hikari:
      max-lifetime: 1800000  #连接的最大生命周期，表示一个连接在被关闭之前的最长使用时间。设置为30分钟（1800000毫秒）
  data:
    redis:
        port: 6379
        host: mpw:VlxmNwZH3XgRYqG/XKMXhg==
        password: mpw:OfGZyCjRemMXVySW/DkUWA==
        database: 0
